### ISSUE TITLE
command 'dotnet-test-explorer.stop' not found

### ISSUE THREAD

**Issue by Ethax** [formulahendry/vscode-dotnet-test-explorer#229]
I've just updated my Visual Studio Code to the newest version:

```yaml
Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763
```
My **.NET Core SDK** version in use is `2.2.300`.

When I click to **Test** on **Activity Bar**, the **.NET Core Test Explorer** automatically starts to discover tests but never stops. If I try to _refresh_, _read the log_ or _stop it_ the following error messages will show up:

![image](https://user-images.githubusercontent.com/10935967/63643214-dffbe980-c6cb-11e9-97fb-98f9431d0fe9.png)

The installed extensions are the following:

```yaml
c-cpp-project-generator: v1.1.1
calculate: v2.1.0
cmake: v0.0.17
code-settings-sync: v3.4.2
cpptools: v0.25.0
csharp: v1.21.1
csharpextensions: v1.3.0
dotnet-test-explorer: v0.7.1
git-graph: v1.13.0
git-merger: v0.4.1
include-autocomplete: v0.0.4
ini-for-vscode: v0.0.4
markdown-all-in-one: v2.4.2
remote-wsl: v0.39.2
sort-lines: v1.8.0
vscode-catch2-test-adapter: v2.6.6
vscode-test-explorer: v2.14.3
vscode-totalcommander: v1.0.4
xml: v2.5.0
```

Do you have any idea what could cause this?
